version: '3'

tasks:
  build-host:
    cmds:
      - echo "Building host kernel..."
      - ${SH_PATH}/build-env/compile_host.sh
      - ${SH_PATH}/compile/kernel.sh -k ${PROJ_PATH}/host-kernel -c ${PROJ_PATH}/config/kernel/host_defconfig
      - ${SH_PATH}/install/kernel.sh -k ${PROJ_PATH}/host-kernel
  compile-guest:
    cmds:
      - echo "Compiling guest kernel..."
      - ${SH_PATH}/build-env/compile_guest.sh
      - ${SH_PATH}/compile/kernel.sh -k ${PROJ_PATH}/guest-kernel -c ${PROJ_PATH}/config/kernel/guest_defconfig
  compile-qemu:
    cmds:
      - echo "Compiling qemu..."
      - ${SH_PATH}/build-env/compile_qemu.sh
      - ${SH_PATH}/compile/qemu.sh
  compile-syzkaller:
    cmds:
      - echo "Compiling syzkaller..."
      - ${SH_PATH}/fetch/syzkaller.sh
      - ${SH_PATH}/build-env/compile_syzkaller.sh
      - ${SH_PATH}/compile/syzkaller.sh
  run-vm:
    cmds:
      - echo "Running vm..."
      - ${PYTHON} ${PY_PATH}/run/vm.py
  run-syzkaller:
      - echo "Running syzkaller..."
      - ${PYTHON} ${PY_PATH}/gen_syz_config.py
  reload-env:
    cmds:
      - echo "Reloading env..."
      - cp /storage/PMIinDriFuzz/scripts/sh/build-env/.bashrc ~/.bashrc
      - source /storage/PMIinDriFuzz/scripts/sh/build-env/.bashrc
