version: '3'

tasks:
  build-host:
    cmds:
      - echo "Building host kernel..."
      - ${SH_PATH}/build-env/compile_host.sh
      - ${SH_PATH}/compile/kernel.sh -k ${PROJ_PATH}/host-kernel -c ${PROJ_PATH}/config/kernel/host_defconfig -b n
      - ${SH_PATH}/install/kernel.sh -k ${PROJ_PATH}/host-kernel
  build-guest-env:
      - echo "Buiding guest kernel environment..."
      - ${SH_PATH}/build-env/compile_guest.sh
  build-qemu-env:
      - echo "Buiding qemu environment..."
      - ${SH_PATH}/build-env/compile_qemu.sh
  build-syzkaller-env:
      - echo "Buiding syzkaller environment..."
      - ${SH_PATH}/fetch/syzkaller.sh
      - ${SH_PATH}/build-env/compile_syzkaller.sh
  build-image:
    cmds:
      - ${SH_PATH}/build/image.sh
  compile-guest:
    cmds:
      - echo "Compiling guest kernel..."
      - ${SH_PATH}/compile/kernel.sh -k ${PROJ_PATH}/guest-kernel -c ${PROJ_PATH}/config/kernel/guest_defconfig -d def
  compile-qemu:
    cmds:
      - echo "Compiling qemu..."
      - ${SH_PATH}/compile/qemu.sh
  compile-syzkaller:
    cmds:
      - echo "Compiling syzkaller..."
      - ${SH_PATH}/compile/syzkaller.sh
  install-modules:
    cmds:
      - ${SH_PATH}/install/module.sh -b /storage/PMIinDriFuzz/build/kernel/main/def
      - ${SH_PATH}/vm/copy-modules.sh /storage/PMIinDriFuzz/build/kernel/image /storage/PMIinDriFuzz/build/image/stretch.img
  run-vm:
    cmds:
      - echo "Running vm..."
      - ${SH_PATH}/run/vm.sh
  run-syzkaller:
      - echo "Running syzkaller..."
      - ${PYTHON} ${PY_PATH}/gen_syz_config.py --branch main --driver bochs --driver_type pci
      - ${SYZ_PATH}/bin/syz-manager -config ${CONFIG_PATH}/fuzzer/syzkaller/pci/bochs.cfg -debug
  ivshmem:
      - make -C /storage/PMIinDriFuzz/scripts/c/module/ivshmem_pci
      - scp -P 1569 -i /storage/PMIinDriFuzz/build/test-image/stretch.id_rsa /storage/PMIinDriFuzz/scripts/c/module/ivshmem_pci/ivshmem_pci.ko root@localhost:~/ivshmem_pci.ko
  reload-env:
    cmds:
      - echo "Reloading env..."
      - cp /storage/PMIinDriFuzz/scripts/sh/build-env/.bashrc ~/.bashrc
      - source /storage/PMIinDriFuzz/scripts/sh/build-env/.bashrc
